### ISSUE TITLE
Problem with unzip

### ISSUE THREAD

**Issue by rdmueller** [ronnypolley/posh-sdkman#25]
I had some problems installing tools. I always got

> WARNING: Could not unzip the archive of doctoolchain 2.0.1. Please delete archive from C:\Users\ralfd\.posh_sdk\.meta\archives (or delete all with 'sdk flush archives'

I debugged it a bit and noticed that it wasn't a problem with the `archives` folder but with the `temp` folder. 
I already contained an item and this the number of items in this folder after unzipping was !=1

https://github.com/ronnypolley/posh-sdkman/blob/develop/PSSDKMan/Utils.ps1#L432

I wonder if it would make sense to clean up the temp folder before we execute the install command?

**Comment by ronnypolley** [comment]
fixed with PR from @rdmueller
